project:
  type: book

format:
  html:
    theme:
      light: flatly
      dark: darkly

book:
# the next option enbale the reader-mode. It hides to TOC and the otpion seems the be automatically enabled by default on Chromium
  #reader-mode: true
  repo-url: https://github.com/fennicahub/fennica
  repo-actions: issue
  sidebar:
    border: true
    title: Harmonized Finnish National Bibliography
    tools:
      - icon: twitter
        href: https://twitter.com/intent/tweet?text=Harmonized%20Finnish%20National%20Bibliography
      - icon: facebook
        href: https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Ffennica-fennica.rahtiapp.fi%2Findex.html


  # files with '##' are the one that need to be corrected
  chapters:
  - index.qmd
  - author_name.qmd
  - author_date.qmd
  - gender.qmd
  - author_profession.qmd
  #- kanto_author_info.qmd
  #- corporate.qmd
  - genre_655.qmd
  - genre_008.qmd
  - language.qmd
  #- physical_dimensions.qmd
  #- physical_extent.qmd
  #- holder.qmd
  #- note_dissertation.qmd
  #- note_granter.qmd
  #- note_source.qmd
  - publisher.qmd
  ##- publication_interval.qmd
  - publication_place.qmd
  - publication_time.qmd
  ##- publication_frequency.qmd
  - signum.qmd
  - title.qmd
  - title_remainder.qmd
  #- title2.qmd
  - content_type.qmd
  - udk.qmd
  #- title_uniform.qmd
  ##- subject_topic.qmd
  #- successor.qmd
  #- uncontrolled.qmd
  - harmonized_fennica.qmd
  appendices :
    - acknowledgments.qmd
    - technical_information.qmd
